### ISSUE TITLE
Croatia Regions

### ISSUE THREAD

**Issue by Kola124** [EdouardSaladier/Magna-Europa-Reloaded#1]
I would recommend renaming Prigorje to Zagreb in reality it is more close to Slovenia then Zagorje. Reference of Zagorje(Behind the mountina) and Prigorje(Near the mountian) is Medvednica. Also rename Gora to Banovina give it South Eastren province of current Prigorje.

**Comment by Kola124** [comment]
I would also ask if this is final states map of mod so i can maybe start working on formable nations mod for this version too.

**Comment by EdouardSaladier** [comment]
I used that map for the Croatia's regions (the Counties of the Independent State of Croatia in 1941-1943):
https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/NezavisnaDrzavaHrvatska.png/1280px-NezavisnaDrzavaHrvatska.png

**Comment by Kola124** [comment]
This is interesting i never saw that map we had different maps in our school books with administrative regions close counties in todays Croatia. It was probably half arsed by publisher so he mashed up modern bosnian and croatian counties. I always tought about that map from school.
